name: tiamat
version: 0.5.0-1
description: This is an emulator of the COMET2 and a compiler of the CASL2.
repository: https://github.com/a-skua/tiamat

environment:
  sdk: ">=2.14.0 <3.0.0"
dev_dependencies:
  test: ^1.16.0-nullsafety.13
  pedantic: ^1.10.0-nullsafety.3
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  analyzer: ^1.7.2
