name: tiamat
version: 0.1.0
authors:
- asuka y <yagi.asuka.0x06@gmail.com>
descriptions: This is an emulator of the COMET2 and a compiler of the CASL2.
repository: https://github.com/a-skua/tiamat

environment:
  sdk: ">=2.12.0-0 <3.0.0"
dev_dependencies:
  test: ^1.16.0-nullsafety.13
