name: tiamat
version: 1.0.0-rc1
description: This is an emulator of the COMET2 and a compiler of the CASL2.
repository: https://github.com/a-skua/tiamat

environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  test: ^1.18.1
  pedantic: ^1.11.1
  build_runner: ^2.0.6
  build_web_compilers: ^4.0.4
  analyzer: ^6.0.0
